@startuml use_case
left to right direction

actor ユーザー
actor 管理ユーザー
rectangle ユースケース {
    usecase アーティストが出演するライブ情報を受け取る
    usecase 通知を受け取るアーティストを登録
    usecase ライブ情報を登録
    usecase ライブ情報を削除
    usecase アーティスト情報を登録
    usecase アーティスト情報を削除
}


ユーザー --> (アーティストが出演するライブ情報を受け取る)
ユーザー --> (通知を受け取るアーティストを登録)
ユーザー --> (通知を受け取るアーティストを登録)
管理ユーザー --> (ライブ情報を登録)
管理ユーザー --> (ライブ情報を削除)
管理ユーザー --> (アーティスト情報を登録)
管理ユーザー --> (アーティスト情報を削除)
@enduml
